//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPTO_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReceitasXPTOEntities : DbContext
    {
        public ReceitasXPTOEntities()
            : base("name=ReceitasXPTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<GrauDificuldade> GrauDificuldade { get; set; }
        public virtual DbSet<Ingredientes> Ingredientes { get; set; }
        public virtual DbSet<Quantidade> Quantidade { get; set; }
        public virtual DbSet<Receita> Receita { get; set; }
        public virtual DbSet<Utilizador> Utilizador { get; set; }
    }
}
