//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPTO_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receita
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Receita()
        {
            this.Ingredientes = new HashSet<Ingredientes>();
            this.Utilizador = new HashSet<Utilizador>();
        }
    
        public int ReceitaID { get; set; }
        public int CategoriaID { get; set; }
        public int DificuldadeID { get; set; }
        public string ReceitaNome { get; set; }
        public string Descrição { get; set; }
        public short Duração { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual GrauDificuldade GrauDificuldade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingredientes> Ingredientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utilizador> Utilizador { get; set; }
    }
}
